#!/usr/bin/python
from tkinter import *
from tkinter import messagebox

#Measurements used to define buttons:
button_height=1
button_width=3
font_size=90
count=1	#Variable used to track number of moves that have been made. Used to determine X or O symbol when buttons are clicked.


def toggle_X_O(string_variable): #Used to switch between X or O after every button click.
  global count
  if string_variable.get()=="":
          if count%2==0:
                  string_variable.set("O")
          elif count%2==1:
                  string_variable.set("X")
          count=count+1

def evaluate_conditions(String1,String2,String3,String4,String5,String6,String7,String8,String9,count):	#Used to store all game end events, and to check the game condition against those events after every button click.
	player="X"
#Vertical X Winning Scenarios:
	if String1.get()==player and String4.get()==player and String7.get()==player:
		messagebox.showinfo(message="X wins!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
	elif String2.get()==player and String5.get()==player and String8.get()==player:
		messagebox.showinfo(message="X wins!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
	elif String3.get()==player and String6.get()==player and String9.get()==player:
		messagebox.showinfo(message="X wins!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
#Horizontal X Winning Scenarios:
	elif String1.get()==player and String2.get()==player and String3.get()==player:
		messagebox.showinfo(message="X wins!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
	elif String4.get()==player and String5.get()==player and String6.get()==player:
		messagebox.showinfo(message="X wins!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
	elif String7.get()==player and String8.get()==player and String9.get()==player:
		messagebox.showinfo(message="X wins!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
#Diagonal X Winning Scenarios:
	elif String1.get()==player and String5.get()==player and String9.get()==player:
		messagebox.showinfo(message="X wins!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
	elif String3.get()==player and String5.get()==player and String7.get()==player:
		messagebox.showinfo(message="X wins!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
	elif count==9:
		messagebox.showinfo(message="It's a draw!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
	
	player="O"
#Vertical O Winning Scenarios:
	if String1.get()==player and String4.get()==player and String7.get()==player:
		messagebox.showinfo(message="O wins!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
	elif String2.get()==player and String5.get()==player and String8.get()==player:
		messagebox.showinfo(message="O wins!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
	elif String3.get()==player and String6.get()==player and String9.get()==player:
		messagebox.showinfo(message="O wins!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
#Horizontal O Winning Scenarios:
	elif String1.get()==player and String2.get()==player and String3.get()==player:
		messagebox.showinfo(message="O wins!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
	elif String4.get()==player and String5.get()==player and String6.get()==player:
		messagebox.showinfo(message="O wins!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
	elif String7.get()==player and String8.get()==player and String9.get()==player:
		messagebox.showinfo(message="O wins!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
#Diagonal O Winning Scenarios:
	elif String1.get()==player and String5.get()==player and String9.get()==player:
		messagebox.showinfo(message="O wins!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)
	elif String3.get()==player and String5.get()==player and String7.get()==player:
		messagebox.showinfo(message="O wins!")
		reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9)

def reset_game(String1,String2,String3,String4,String5,String6,String7,String8,String9):
	String1.set("")
	String2.set("")
	String3.set("")
	String4.set("")
	String5.set("")
	String6.set("")
	String7.set("")
	String8.set("")
	String9.set("")
	global count
	count=1

def commandbutton(string_variable,String1,String2,String3,String4,String5,String6,String7,String8,String9,count):#evaluate conditions doesn't like globals. Might have to manually input each as an argument.
	toggle_X_O(string_variable)
	evaluate_conditions(String1,String2,String3,String4,String5,String6,String7,String8,String9,count)

def __main__(): #Main loop.
  window=Tk()
  window.title("Tic Tac Toe")

  String1=StringVar()
  button1=Button(window,textvariable=String1,height=button_height,width=button_width,command=lambda:commandbutton(String1,String1,String2,String3,String4,String5,String6,String7,String8,String9,count))
  button1.grid(row=0,column=0)
  button1.config(font=('helvetica',font_size))


  String2=StringVar()
  button2=Button(window,textvariable=String2,height=button_height,width=button_width,command=lambda:commandbutton(String2,String1,String2,String3,String4,String5,String6,String7,String8,String9,count))
  button2.grid(row=0,column=1)
  button2.config(font=('helvetica',font_size))


  String3=StringVar()
  button3=Button(window,textvariable=String3,height=button_height,width=button_width,command=lambda:commandbutton(String3,String1,String2,String3,String4,String5,String6,String7,String8,String9,count))
  button3.grid(row=0,column=2)
  button3.config(font=('helvetica',font_size))


  String4=StringVar()
  button4=Button(window,textvariable=String4,height=button_height,width=button_width,command=lambda:commandbutton(String4,String1,String2,String3,String4,String5,String6,String7,String8,String9,count))
  button4.grid(row=1,column=0)
  button4.config(font=('helvetica',font_size))


  String5=StringVar()
  button5=Button(window,textvariable=String5,height=button_height,width=button_width,command=lambda:commandbutton(String5,String1,String2,String3,String4,String5,String6,String7,String8,String9,count))
  button5.grid(row=1,column=1)
  button5.config(font=('helvetica',font_size))


  String6=StringVar()
  button6=Button(window,textvariable=String6,height=button_height,width=button_width,command=lambda:commandbutton(String6,String1,String2,String3,String4,String5,String6,String7,String8,String9,count))
  button6.grid(row=1,column=2)
  button6.config(font=('helvetica',font_size))


  String7=StringVar()
  button7=Button(window,textvariable=String7,height=button_height,width=button_width,command=lambda:commandbutton(String7,String1,String2,String3,String4,String5,String6,String7,String8,String9,count))
  button7.grid(row=2,column=0)
  button7.config(font=('helvetica',font_size))


  String8=StringVar()
  button8=Button(window,textvariable=String8,height=button_height,width=button_width,command=lambda:commandbutton(String8,String1,String2,String3,String4,String5,String6,String7,String8,String9,count))
  button8.grid(row=2,column=1)
  button8.config(font=('helvetica',font_size))


  String9=StringVar()
  button9=Button(window,textvariable=String9,height=button_height,width=button_width,command=lambda:commandbutton(String9,String1,String2,String3,String4,String5,String6,String7,String8,String9,count))
  button9.grid(row=2,column=2)
  button9.config(font=('helvetica',font_size))
  window.mainloop()
#Let the games begin!
if __name__=="__main__":
	__main__()
